version: "3.9"
services:
  tracker:
    build: tracker
    ports:
      - "6969:6969"
  mqtt:
    build: mqtt
    ports:
      - "1883:1883"
  seeder:
    build: seeder
    tty: true
    ports:
      - "6890:6899"
  leecher:
    build: leecher
    tty: true
    ports:
      - "6990:6999"
