#!/bin/bash
# ensure we're binding to the right, arbitrarily assigned IP
sed -e "s/~HOSTNAME_I~/$(hostname -i)/g" /root/.rtorrent.rc.tpl > /root/.rtorrent.rc
echo "screen -x" > /root/.bash_history

# Wait for the leecher to come up
EXIT=14
while [ ${EXIT} -ne 0 ]; do
  mosquitto_sub -h mqtt -p 1883 -t "control" -C 1 2>/dev/null | grep -q "ok to go" 
  EXIT=$?
  sleep 1
done

# start screen detached, which will fire up rtorrent
ps -ef | grep -v grep | grep SCREEN
EXIT=$?
while [ ${EXIT} -ne 0 ]; do
  screen -d -m > /var/log/screen.log 2>&1
  EXIT=$?
  sleep 1
done
echo ${EXIT} > /var/log/screen.exit

# Create our torrent
/bin/dd if=/dev/urandom of=/opt/rtorrent/download/start/torrentfile bs=512 count=10240 > /dev/null 2>&1
sha1sum /opt/rtorrent/download/start/torrentfile
[ -f /opt/rtorrent/watch/start/torrentfile.torrent ] && rm -f /opt/rtorrent/watch/start/torrentfile.torrent
/usr/bin/mktorrent -v -p -a http://$(dig +short tracker):6969/announce -o /tmp/torrentfile.torrent /opt/rtorrent/download/start/torrentfile > /dev/null 2>&1
transmission-show /tmp/torrentfile.torrent > /dev/null 2>&1 && mv /tmp/torrentfile.torrent /opt/rtorrent/watch/start/torrentfile.torrent

# send the torrent to the leecher
mosquitto_pub -h mqtt -t torrent -m "$(cat /opt/rtorrent/watch/start/torrentfile.torrent | base64 -w 0)"

# wait for the download to complete then exit
EXIT=1
while [ ${EXIT} -ne 0 ]; do
  mosquitto_sub -h mqtt -p 1883 -t "finish" -C 1 | grep -q "^download completed$"
  EXIT=$?
  sleep 3
done
