#!/bin/bash
DEBUG="true"
unset DEBUG
# ensure we're binding to the right, arbitrarily assigned IP
sed -e "s/~HOSTNAME_I~/$(hostname -i)/g" /root/.rtorrent.rc.tpl > /root/.rtorrent.rc
echo "screen -x" > /root/.bash_history
echo -e "syntax on\nset background=dark" > /root/.vimrc

# let the seeder know we up, persist the message in case the seeder isn't awake yet, this message gets it all rolling
EXIT=14
while [ ${EXIT} -ne 0 ]; do
  mosquitto_pub -h mqtt -p 1883 -t "control" -r -m "ok to go" 2>/dev/null
  EXIT=$?
  sleep 1
done

# start screen detached, which will fire up rtorrent
ps -ef | grep -v grep | grep SCREEN
EXIT=$?
while [ ${EXIT} -ne 0 ]; do
  screen -d -m > /var/log/screen.log 2>&1
  EXIT=$?
  sleep 1
done
echo ${EXIT} > /var/log/screen.exit

# wait for the seeder to send us our torrent file, but don't try to start a download on an empty file
mosquitto_sub -h mqtt -t "torrent" -C 1 | base64 -d > /tmp/torrentfile.torrent
transmission-show /tmp/torrentfile.torrent > /dev/null 2>&1 && mv /tmp/torrentfile.torrent /opt/rtorrent/watch/start/torrentfile.torrent

# wait for the file to finish downloading and get moved
while [ ! -f /opt/rtorrent/download/hit-and-run/torrentfile ]; do
  mosquitto_pub -h mqtt -p 1883 -t "test" -r -m "still waiting on download to complete"
  sleep 10
done

# wait for the file to finish hit-and-run and get moved to seed
while [ ! -f /opt/rtorrent/download/seed/torrentfile ]; do
  mosquitto_pub -h mqtt -p 1883 -t "test" -r -m "still waiting on hit-and-run to expire"
  sleep 10
done
sha1sum /opt/rtorrent/download/seed/torrentfile

if [ ! -z "${DEBUG}" ]; then
# wait for the download to complete then exit (normally we send this but this is for debugging, send it from your workstation)
  EXIT=1
  while [ ${EXIT} -ne 0 ]; do
    mosquitto_sub -h mqtt -p 1883 -t "finish" -C 1 | grep -q "^download completed$"
    EXIT=$?
    sleep 3
  done
else
  # let the containers know we're done and exit (uncomment when not debugging containers)
  mosquitto_pub -h mqtt -p 1883 -t "finish" -m "download completed"
fi
