#!/bin/bash
# ensure we're binding to the right, arbitrarily assigned IP
sed -e "s/~HOSTNAME_I~/$(hostname -i)/g" /root/.rtorrent.rc.tpl > /root/.rtorrent.rc

# start screen detached, which will fire up rtorrent
sleep 5; screen -d -m

# let the seeder know we up, persist the message in case the seeder isn't awake yet, this message gets it all rolling
EXIT=14
while [ ${EXIT} -ne 0 ]; do
  mosquitto_pub -h mqtt -p 1883 -t "control" -r -m "ok to go"
  EXIT=$?
  sleep 1
done

# wait for the seeder to send us our torrent file, but don't try to start a download on an empty file
mosquitto_sub -h mqtt -t "torrent" -C 1 | base64 -d > /tmp/torrentfile.torrent
transmission-show /tmp/torrentfile.torrent && mv /tmp/torrentfile.torrent /opt/rtorrent/watch/start/torrentfile.torrent

# wait forever
/bin/bash
