#!/bin/bash
/usr/sbin/mosquitto -d > /var/log/mosquitto.stdout 2>/var/log/mosquitto.stderr

# wait for the download to complete then exit
EXIT=1
while [ ${EXIT} -ne 0 ]; do
  mosquitto_sub -h mqtt -p 1883 -t "finish" -C 1 | grep -q "^download completed$"
  EXIT=$?
  sleep 3
done
