on: pull_request
jobs:
  integration-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: docker-compose up --build --force-recreate --remove-orphans --exit-code-from leecher
