version: "2"
on: [push, pull_request]
jobs:
  build:
    runs-on: scratch
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: docker-compose up --build --force-recreate --remove-orphans --exit-code-from leecher
